#!/bin/bash
echo "---START---"
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install mosquitto -y
sudo apt-get install mosquitto-clients -y
cat > /etc/mosquitto/mosquitto.conf <<EOL
# Place your local configuration in /etc/mosquitto/conf.d/
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

pid_file /run/mosquitto/mosquitto.pid

persistence true

persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d

allow_anonymous true

listener 1883

EOL
echo "---END---"
sudo reboot
