#!/bin/bash
echo "---NODE---"
# sudo curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
# sudo apt-get install -y nodejs git make g++ gcc
echo "---Z2M---"
sudo mkdir /opt/zigbee2mqtt
sudo git clone https://github.com/Koenkk/zigbee2mqtt.git /opt/zigbee2mqtt
cd /opt/zigbee2mqtt
git fetch
git checkout master
git config pull.rebase false  # merge
npm ci
sudo chown -R ${USER}: /opt/zigbee2mqtt
echo "---CONF---"
cat > /opt/zigbee2mqtt/data/configuration.yaml <<EOL
# Home Assistant integration (MQTT discovery)
homeassistant: false

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for Zigbee2MQTT MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://192.168.1.5:1883'
  # MQTT server authentication, uncomment if required:
  # user: mqtt
  # password: mqtt

# Serial settings
serial:
  # Location of the adapter (see first step of this guide)
  port: /dev/ttyUSB0

frontend:
  # Optional, default 8080 or you can use your own as well.
  port: 8080
  # IP address of the device running Zigbee2MQTT
  host: 192.168.1.5
advanced:
  log_level: debug
  network_key: GENERATE
EOL
echo "---SERVICE---"
cat > /etc/systemd/system/zigbee2mqtt.service <<EOL
[Unit]
Description=zigbee2mqtt
After=network.target

[Service]
ExecStart=npm start
WorkingDirectory=/opt/zigbee2mqtt
StandardOutput=null
StandardError=inherit
Restart=always
User=andrsi

[Install]
WantedBy=multi-user.target
EOL
echo "---END---"
sudo systemctl enable zigbee2mqtt.service
sudo reboot
